#!/usr/bin/env bash

### ### HEAT MAP CD UTILITIES ### ###

###override CD 
function cd(){
    builtin cd "$@"
    echo "1 $(pwd)" >> ${DirHeatMap}
}

function _crunch() {
    awk '{map[$2]+=$1}END{for(dir in map)print map[dir] " " dir}'
}

###CLEAN HCD of missing files
function clean_hcd() {
    local TempMap
    TempMap=/tmp/temp_$(basename $DirHeatMap)
    cat $DirHeatMap | awk '{print "if [ -d "$2" ]; then echo "$1" "$2"; fi" }'| bash > $TempMap
    cat $TempMap > $DirHeatMap
    rm $TempMap
}

###Heat map CD
function hcd(){
    local SearchTerm
    SearchTerm="$1"
    local Count=1
    local TargetDir
    local TempMap
    TempMap=/tmp/temp_$(basename $DirHeatMap)
    cat $DirHeatMap | _crunch | sort -nk1 > $TempMap
    cat $TempMap > $DirHeatMap
    rm $TempMap
    if [ $# -eq 0 ]
    then
        cat ${DirHeatMap}
        return 0
    fi
    if [ $# -gt 1 ]
    then
        Count=$2
    fi
    TargetDir=$(cat ${DirHeatMap} | grep "$SearchTerm" | awk '{print $2}' | tail -$Count | head -1)
    if [ -z $TargetDir ]
    then
        _error_echo "No Matches for $@"
        return 1
    fi
    cd $TargetDir
}

