#!/usr/bin/env bash

### ### MAC SPECIFIC UTILITIES ### ###

if [ "$ShaOS" != "darwin" ]
then
    _error_echo "Not sourcing mac aliases since $ShaOS != darwin."
    return 0
fi

###Copy Git Match
function cgm() {
    local Hits
    Hits=$(fgfm "$1")
    if [ $( echo $Hits | wc -w ) -ne 1 ]
    then
        _error_echo "Wrong number of hits: $Hits"
        return 1
    else
        echo "$Hits" | tr -d '\n' | pbcopy
    fi
}
complete -F _complete_for_fgm cgm

###Copy TIME:
function ctime(){
    local DateDelim
    local DateTimeDelim
    local TimeDelim
    TimeDelim=":"
    DateTimeDelim=" "
    DateDelim="-"
    if [ $# -gt 0 ] 
    then
        DateDelim="$1"
    fi  
    date "+%Y${DateDelim}%m${DateDelim}%d${DateTimeDelim}%H${TimeDelim}%M" | tr -d '\n' | pbcopy
}

###Copy DATE:
function cdate(){
    local Delim
    Delim="-"
    if [ $# -gt 0 ] 
    then
        Delim="$1"
    fi  
    date "+%Y${Delim}%m${Delim}%d" | tr -d '\n' | pbcopy
}

